// Central UI-string translations, keyed by the English text.
// Lets inline `isZh ? '中' : 'EN'` become `tr('EN', language)` for all 6 langs.
// ja / ko / th are best-effort — native review recommended.

type Lang = 'en' | 'zh-CN' | 'zh-TW' | 'ja' | 'ko' | 'th';

const UI: Record<string, Partial<Record<Lang, string>>> = {
  'Add': { 'zh-CN': '添加', 'zh-TW': '新增', ja: '追加', ko: '추가', th: 'เพิ่ม' },
  'All Church': { 'zh-CN': '全教会', 'zh-TW': '全教會', ja: '全教会', ko: '전교회', th: 'ทั้งคริสตจักร' },
  'Staff': { 'zh-CN': '同工', 'zh-TW': '同工', ja: 'スタッフ', ko: '사역자', th: 'เจ้าหน้าที่' },
  'Pastors Only': { 'zh-CN': '仅牧者', 'zh-TW': '僅牧者', ja: '牧師のみ', ko: '목회자 전용', th: 'เฉพาะศิษยาภิบาล' },
  'My Eyes Only': { 'zh-CN': '仅自己可见', 'zh-TW': '僅自己可見', ja: '自分のみ', ko: '나만 보기', th: 'เฉพาะฉัน' },
  'Administrator View': { 'zh-CN': '管理员视图', 'zh-TW': '管理員視圖', ja: '管理者ビュー', ko: '관리자 보기', th: 'มุมมองผู้ดูแล' },
  'All Departments': { 'zh-CN': '所有岗位', 'zh-TW': '所有崗位', ja: '全部門', ko: '모든 부서', th: 'ทุกหน้าที่' },
  'All Saved': { 'zh-CN': '全部已保存', 'zh-TW': '全部已儲存', ja: 'すべて保存済み', ko: '모두 저장됨', th: 'บันทึกทั้งหมดแล้ว' },
  'Anonymous to Church': { 'zh-CN': '对教会匿名', 'zh-TW': '對教會匿名', ja: '教会に匿名', ko: '교회에 익명', th: 'ไม่ระบุชื่อต่อคริสตจักร' },
  'Auto Fill': { 'zh-CN': '自动排班', 'zh-TW': '自動排班', ja: '自動入力', ko: '자동 채우기', th: 'เติมอัตโนมัติ' },
  'Awaiting approval — visible to everyone once approved': { 'zh-CN': '等待管理员审核中，审核通过后所有人可见', 'zh-TW': '等待管理員審核中，審核通過後所有人可見', ja: '承認待ち — 承認されると全員に表示されます', ko: '승인 대기 중 — 승인되면 모두에게 표시됩니다', th: 'รออนุมัติ — เมื่ออนุมัติแล้วทุกคนจะเห็น' },
  'Call': { 'zh-CN': '致电', 'zh-TW': '致電', ja: '電話', ko: '전화', th: 'โทร' },
  'Cancel': { 'zh-CN': '取消', 'zh-TW': '取消', ja: 'キャンセル', ko: '취소', th: 'ยกเลิก' },
  'Category (e.g. Ministry)': { 'zh-CN': '分类（例如：事工）', 'zh-TW': '分類（例如：事工）', ja: 'カテゴリ（例：奉仕）', ko: '카테고리 (예: 사역)', th: 'หมวดหมู่ (เช่น พันธกิจ)' },
  'Description': { 'zh-CN': '描述', 'zh-TW': '描述', ja: '説明', ko: '설명', th: 'คำอธิบาย' },
  'Done': { 'zh-CN': '已完成', 'zh-TW': '已完成', ja: '完了', ko: '완료', th: 'เสร็จสิ้น' },
  'Due Date': { 'zh-CN': '截止日期', 'zh-TW': '截止日期', ja: '期限', ko: '마감일', th: 'กำหนดส่ง' },
  'Email': { 'zh-CN': '邮箱', 'zh-TW': '郵箱', ja: 'メール', ko: '이메일', th: 'อีเมล' },
  'Group': { 'zh-CN': '小组', 'zh-TW': '小組', ja: 'グループ', ko: '그룹', th: 'กลุ่ม' },
  'High': { 'zh-CN': '高', 'zh-TW': '高', ja: '高', ko: '높음', th: 'สูง' },
  'In Progress': { 'zh-CN': '进行中', 'zh-TW': '進行中', ja: '進行中', ko: '진행 중', th: 'กำลังดำเนินการ' },
  'Job Title': { 'zh-CN': '工作职称', 'zh-TW': '工作職稱', ja: '役職', ko: '직책', th: 'ตำแหน่งงาน' },
  'Low': { 'zh-CN': '低', 'zh-TW': '低', ja: '低', ko: '낮음', th: 'ต่ำ' },
  'Medium': { 'zh-CN': '中', 'zh-TW': '中', ja: '中', ko: '보통', th: 'ปานกลาง' },
  'Membership Status': { 'zh-CN': '成员身份', 'zh-TW': '成員身份', ja: 'メンバーシップ', ko: '멤버십 상태', th: 'สถานะสมาชิก' },
  'Month View': { 'zh-CN': '月视图', 'zh-TW': '月視圖', ja: '月表示', ko: '월 보기', th: 'มุมมองรายเดือน' },
  'New Task': { 'zh-CN': '新建任务', 'zh-TW': '新增任務', ja: '新規タスク', ko: '새 작업', th: 'งานใหม่' },
  'New group name...': { 'zh-CN': '新建小组名称...', 'zh-TW': '新增小組名稱...', ja: '新しいグループ名...', ko: '새 그룹 이름...', th: 'ชื่อกลุ่มใหม่...' },
  'New groups sync to the Groups page': { 'zh-CN': '新建的小组会同步到「小组」页面', 'zh-TW': '新增的小組會同步到「小組」頁面', ja: '新しいグループは「グループ」ページに同期されます', ko: '새 그룹은 그룹 페이지에 동기화됩니다', th: 'กลุ่มใหม่จะซิงค์ไปยังหน้ากลุ่ม' },
  'No group': { 'zh-CN': '无小组', 'zh-TW': '無小組', ja: 'グループなし', ko: '그룹 없음', th: 'ไม่มีกลุ่ม' },
  'No skills added yet': { 'zh-CN': '暂未填写技能', 'zh-TW': '尚未填寫技能', ja: 'スキル未登録', ko: '등록된 기술 없음', th: 'ยังไม่มีทักษะ' },
  'Once approved by a manager, your prayer will be visible to everyone.': { 'zh-CN': '管理员审核通过后，你的祷告将对所有人可见。', 'zh-TW': '管理員審核通過後，你的禱告將對所有人可見。', ja: '管理者が承認すると、あなたの祈りは全員に表示されます。', ko: '관리자가 승인하면 기도가 모두에게 표시됩니다.', th: 'เมื่อผู้ดูแลอนุมัติ คำอธิษฐานของคุณจะปรากฏต่อทุกคน' },
  'PDF production failed. Try printing the page or use a desktop browser.': { 'zh-CN': 'PDF 生成失败。请尝试打印页面，或使用桌面浏览器。', 'zh-TW': 'PDF 產生失敗。請嘗試列印頁面，或使用桌面瀏覽器。', ja: 'PDFの生成に失敗しました。ページを印刷するかデスクトップブラウザをお使いください。', ko: 'PDF 생성 실패. 페이지를 인쇄하거나 데스크톱 브라우저를 사용하세요.', th: 'สร้าง PDF ไม่สำเร็จ ลองพิมพ์หน้านี้หรือใช้เบราว์เซอร์บนเดสก์ท็อป' },
  'Pastoral Management Dashboard': { 'zh-CN': '牧养管理面板', 'zh-TW': '牧養管理面板', ja: '牧会管理ダッシュボード', ko: '목양 관리 대시보드', th: 'แดชบอร์ดการดูแลจิตวิญญาณ' },
  'Personnel List': { 'zh-CN': '人员列表', 'zh-TW': '人員列表', ja: '人員リスト', ko: '인원 목록', th: 'รายชื่อบุคลากร' },
  'Priority': { 'zh-CN': '优先级', 'zh-TW': '優先級', ja: '優先度', ko: '우선순위', th: 'ความสำคัญ' },
  'Role': { 'zh-CN': '职位', 'zh-TW': '職位', ja: '役割', ko: '직책', th: 'บทบาท' },
  'Role Settings': { 'zh-CN': '岗位设置', 'zh-TW': '崗位設定', ja: '役割設定', ko: '역할 설정', th: 'ตั้งค่าบทบาท' },
  'Save Error': { 'zh-CN': '保存出错', 'zh-TW': '儲存出錯', ja: '保存エラー', ko: '저장 오류', th: 'บันทึกผิดพลาด' },
  'Saving...': { 'zh-CN': '保存中…', 'zh-TW': '儲存中…', ja: '保存中…', ko: '저장 중…', th: 'กำลังบันทึก…' },
  'Search Member...': { 'zh-CN': '搜索成员…', 'zh-TW': '搜尋成員…', ja: 'メンバー検索…', ko: '멤버 검색…', th: 'ค้นหาสมาชิก…' },
  'Select Member...': { 'zh-CN': '选择成员…', 'zh-TW': '選擇成員…', ja: 'メンバーを選択…', ko: '멤버 선택…', th: 'เลือกสมาชิก…' },
  'Skills & Ministry': { 'zh-CN': '事奉技能', 'zh-TW': '事奉技能', ja: '賜物と奉仕', ko: '은사 및 사역', th: 'ทักษะและพันธกิจ' },
  'Spiritual Family / Group': { 'zh-CN': '所属小组', 'zh-TW': '所屬小組', ja: '所属グループ', ko: '소속 그룹', th: 'กลุ่มสังกัด' },
  'Table List': { 'zh-CN': '列表视图', 'zh-TW': '列表視圖', ja: 'リスト表示', ko: '목록 보기', th: 'มุมมองตาราง' },
  'Task title *': { 'zh-CN': '任务标题 *', 'zh-TW': '任務標題 *', ja: 'タスク名 *', ko: '작업 제목 *', th: 'ชื่องาน *' },
  'Workspace': { 'zh-CN': '工作区', 'zh-TW': '工作區', ja: 'ワークスペース', ko: '작업 공간', th: 'พื้นที่ทำงาน' },
  'e.g. Guitarist, Bassist...': { 'zh-CN': '例如：吉他手、贝斯手…', 'zh-TW': '例如：吉他手、貝斯手…', ja: '例：ギタリスト、ベーシスト…', ko: '예: 기타리스트, 베이시스트…', th: 'เช่น มือกีตาร์ มือเบส…' },
  'e.g. Software Engineer': { 'zh-CN': '例：软件工程师', 'zh-TW': '例：軟體工程師', ja: '例：ソフトウェアエンジニア', ko: '예: 소프트웨어 엔지니어', th: 'เช่น วิศวกรซอฟต์แวร์' },
  '✅ Prayer submitted — awaiting approval': { 'zh-CN': '✅ 祷告已提交，等待审核中', 'zh-TW': '✅ 禱告已提交，等待審核中', ja: '✅ 祈りを送信しました — 承認待ち', ko: '✅ 기도가 제출되었습니다 — 승인 대기 중', th: '✅ ส่งคำอธิษฐานแล้ว — รออนุมัติ' },

  // ── Groups page ────────────────────────────────────────────────────────────
  'en-AU': { 'zh-CN': 'zh-CN', 'zh-TW': 'zh-TW', ja: 'ja', ko: 'ko', th: 'th' }, // date locale mapper
  'Delete this group?': { 'zh-CN': '确定删除这个小组？', 'zh-TW': '確定刪除這個小組？', ja: 'このグループを削除しますか？', ko: '이 그룹을 삭제하시겠습니까?', th: 'ลบกลุ่มนี้?' },
  'Anonymous': { 'zh-CN': '匿名', 'zh-TW': '匿名', ja: '匿名', ko: '익명', th: 'ไม่ระบุชื่อ' },
  'Groups': { 'zh-CN': '小组', 'zh-TW': '小組', ja: 'グループ', ko: '그룹', th: 'กลุ่ม' },
  'Manager · All Groups': { 'zh-CN': '管理员 · 全部小组', 'zh-TW': '管理員 · 全部小組', ja: '管理者 · 全グループ', ko: '관리자 · 전체 그룹', th: 'ผู้ดูแล · ทุกกลุ่ม' },
  'My Group': { 'zh-CN': '我的小组', 'zh-TW': '我的小組', ja: 'マイグループ', ko: '내 그룹', th: 'กลุ่มของฉัน' },
  'No groups yet': { 'zh-CN': '暂无小组', 'zh-TW': '暫無小組', ja: 'グループがありません', ko: '아직 그룹이 없습니다', th: 'ยังไม่มีกลุ่ม' },
  'Not in a group yet': { 'zh-CN': '你还未加入小组', 'zh-TW': '你還未加入小組', ja: 'まだグループに参加していません', ko: '아직 그룹에 속하지 않았습니다', th: 'ยังไม่ได้อยู่ในกลุ่ม' },
  'Ask your manager to add you to a group': { 'zh-CN': '请联系管理员将你加入小组', 'zh-TW': '請聯絡管理員將你加入小組', ja: '管理者にグループへの追加を依頼してください', ko: '관리자에게 그룹 추가를 요청하세요', th: 'ขอให้ผู้ดูแลเพิ่มคุณเข้ากลุ่ม' },
  'members': { 'zh-CN': '人', 'zh-TW': '人', ja: '人', ko: '명', th: 'คน' },
  'Assign members': { 'zh-CN': '分配成员', 'zh-TW': '分配成員', ja: 'メンバーを割り当て', ko: '멤버 배정', th: 'มอบหมายสมาชิก' },
  'Assign Members': { 'zh-CN': '分配成员', 'zh-TW': '分配成員', ja: 'メンバーを割り当て', ko: '멤버 배정', th: 'มอบหมายสมาชิก' },
  'Assign': { 'zh-CN': '分配成员', 'zh-TW': '分配成員', ja: '割り当て', ko: '배정', th: 'มอบหมาย' },
  'New Group': { 'zh-CN': '新建小组', 'zh-TW': '新增小組', ja: '新規グループ', ko: '새 그룹', th: 'กลุ่มใหม่' },
  'Create a group first': { 'zh-CN': '先创建小组', 'zh-TW': '先建立小組', ja: '先にグループを作成', ko: '먼저 그룹을 생성하세요', th: 'สร้างกลุ่มก่อน' },
  'Select a group': { 'zh-CN': '选择一个小组', 'zh-TW': '選擇一個小組', ja: 'グループを選択', ko: '그룹 선택', th: 'เลือกกลุ่ม' },
  'Create groups and use 👤 to assign members': { 'zh-CN': '点击左侧“新建小组”，然后用👤图标分配成员', 'zh-TW': '點擊左側「新增小組」，然後用👤圖示分配成員', ja: 'グループを作成し、👤でメンバーを割り当てます', ko: '그룹을 만들고 👤로 멤버를 배정하세요', th: 'สร้างกลุ่มและใช้ 👤 เพื่อมอบหมายสมาชิก' },
  'Share': { 'zh-CN': '分享内容', 'zh-TW': '分享內容', ja: '共有', ko: '공유', th: 'แบ่งปัน' },
  'Leader': { 'zh-CN': '负责人', 'zh-TW': '負責人', ja: 'リーダー', ko: '리더', th: 'ผู้นำ' },
  'Contact': { 'zh-CN': '联系方式', 'zh-TW': '聯絡方式', ja: '連絡先', ko: '연락처', th: 'ติดต่อ' },
  'Meeting Time': { 'zh-CN': '聚会时间', 'zh-TW': '聚會時間', ja: '集会時間', ko: '모임 시간', th: 'เวลาประชุม' },
  'Meeting Place': { 'zh-CN': '聚会地点', 'zh-TW': '聚會地點', ja: '集会場所', ko: '모임 장소', th: 'สถานที่ประชุม' },
  'Meeting Address': { 'zh-CN': '聚会地点', 'zh-TW': '聚會地點', ja: '集会場所', ko: '모임 장소', th: 'สถานที่ประชุม' },
  'Meeting location': { 'zh-CN': '聚会地址', 'zh-TW': '聚會地址', ja: '集会場所', ko: '모임 위치', th: 'ที่ตั้งการประชุม' },
  'Remove from group': { 'zh-CN': '移出小组', 'zh-TW': '移出小組', ja: 'グループから削除', ko: '그룹에서 제거', th: 'นำออกจากกลุ่ม' },
  'Remove': { 'zh-CN': '移出', 'zh-TW': '移出', ja: '削除', ko: '제거', th: 'นำออก' },
  'Text': { 'zh-CN': '文字', 'zh-TW': '文字', ja: 'テキスト', ko: '텍스트', th: 'ข้อความ' },
  'Link': { 'zh-CN': '链接', 'zh-TW': '連結', ja: 'リンク', ko: '링크', th: 'ลิงก์' },
  'Photo': { 'zh-CN': '照片', 'zh-TW': '照片', ja: '写真', ko: '사진', th: 'รูปภาพ' },
  'Share something with the group...': { 'zh-CN': '写点什么分享给小组...', 'zh-TW': '寫點什麼分享給小組...', ja: 'グループに何か共有...', ko: '그룹에 공유할 내용...', th: 'แบ่งปันบางอย่างกับกลุ่ม...' },
  'Description (optional)': { 'zh-CN': '描述（可选）', 'zh-TW': '描述（可選）', ja: '説明（任意）', ko: '설명 (선택)', th: 'คำอธิบาย (ไม่บังคับ)' },
  'Choose Photo': { 'zh-CN': '选择照片', 'zh-TW': '選擇照片', ja: '写真を選択', ko: '사진 선택', th: 'เลือกรูปภาพ' },
  'Caption (optional)': { 'zh-CN': '添加说明（可选）', 'zh-TW': '新增說明（可選）', ja: 'キャプション（任意）', ko: '캡션 (선택)', th: 'คำบรรยาย (ไม่บังคับ)' },
  'Post': { 'zh-CN': '发布', 'zh-TW': '發佈', ja: '投稿', ko: '게시', th: 'โพสต์' },
  'No posts yet': { 'zh-CN': '还没有分享内容', 'zh-TW': '還沒有分享內容', ja: 'まだ投稿がありません', ko: '아직 게시물이 없습니다', th: 'ยังไม่มีโพสต์' },
  'Click "Share" above to get started': { 'zh-CN': '点击右上角“分享内容”开始', 'zh-TW': '點擊右上角「分享內容」開始', ja: '上の「共有」をクリックして開始', ko: '위의 "공유"를 클릭하여 시작', th: 'คลิก "แบ่งปัน" ด้านบนเพื่อเริ่ม' },
  'In: ': { 'zh-CN': '在：', 'zh-TW': '在：', ja: '所属：', ko: '소속: ', th: 'ใน: ' },
  'Unassigned': { 'zh-CN': '未分配', 'zh-TW': '未分配', ja: '未割り当て', ko: '미배정', th: 'ยังไม่มอบหมาย' },
  'Edit Group': { 'zh-CN': '编辑小组', 'zh-TW': '編輯小組', ja: 'グループを編集', ko: '그룹 편집', th: 'แก้ไขกลุ่ม' },
  'Set group name and colour': { 'zh-CN': '设置小组名称和颜色', 'zh-TW': '設定小組名稱和顏色', ja: 'グループ名と色を設定', ko: '그룹 이름과 색상 설정', th: 'ตั้งชื่อและสีของกลุ่ม' },
  'Group Name *': { 'zh-CN': '小组名称 *', 'zh-TW': '小組名稱 *', ja: 'グループ名 *', ko: '그룹 이름 *', th: 'ชื่อกลุ่ม *' },
  'e.g. Youth Group': { 'zh-CN': '例如：青年小组', 'zh-TW': '例如：青年小組', ja: '例：青年グループ', ko: '예: 청년 그룹', th: 'เช่น กลุ่มเยาวชน' },
  'Brief description': { 'zh-CN': '小组简介', 'zh-TW': '小組簡介', ja: '簡単な説明', ko: '간단한 설명', th: 'คำอธิบายสั้นๆ' },
  'Leader name': { 'zh-CN': '负责人姓名', 'zh-TW': '負責人姓名', ja: 'リーダー名', ko: '리더 이름', th: 'ชื่อผู้นำ' },
  'Phone / WeChat': { 'zh-CN': '电话 / 微信', 'zh-TW': '電話 / 微信', ja: '電話 / WeChat', ko: '전화 / 위챗', th: 'โทรศัพท์ / WeChat' },
  'e.g. Fridays 7:30 PM': { 'zh-CN': '例如：每周五 19:30', 'zh-TW': '例如：每週五 19:30', ja: '例：毎週金曜 19:30', ko: '예: 매주 금요일 오후 7:30', th: 'เช่น ทุกวันศุกร์ 19:30' },
  'Color': { 'zh-CN': '颜色', 'zh-TW': '顏色', ja: '色', ko: '색상', th: 'สี' },
  'Save': { 'zh-CN': '保存修改', 'zh-TW': '儲存變更', ja: '保存', ko: '저장', th: 'บันทึก' },
  'Create Group': { 'zh-CN': '创建小组', 'zh-TW': '建立小組', ja: 'グループを作成', ko: '그룹 생성', th: 'สร้างกลุ่ม' },

  // ── Approvals / Member Management page ──────────────────────────────────────
  'Member Management': { 'zh-CN': '成员管理', 'zh-TW': '成員管理', ja: 'メンバー管理', ko: '멤버 관리', th: 'จัดการสมาชิก' },
  'Manage church members and membership applications': { 'zh-CN': '管理教会成员及入会申请', 'zh-TW': '管理教會成員及入會申請', ja: '教会メンバーと入会申請を管理', ko: '교회 멤버 및 가입 신청 관리', th: 'จัดการสมาชิกคริสตจักรและใบสมัคร' },
  'No matching members found': { 'zh-CN': '没有找到匹配的成员', 'zh-TW': '沒有找到符合的成員', ja: '一致するメンバーが見つかりません', ko: '일치하는 멤버가 없습니다', th: 'ไม่พบสมาชิกที่ตรงกัน' },
  'No matches found': { 'zh-CN': '暂无匹配成员', 'zh-TW': '暫無符合成員', ja: '一致するものがありません', ko: '일치하는 항목 없음', th: 'ไม่พบรายการที่ตรงกัน' },
  'No church members or pending applications match your criteria.': { 'zh-CN': '没有找到符合当前筛选条件的教会成员或待办申请。', 'zh-TW': '沒有符合目前篩選條件的教會成員或待辦申請。', ja: '条件に一致する教会メンバーや申請が見つかりません。', ko: '조건에 맞는 교회 멤버나 신청이 없습니다.', th: 'ไม่พบสมาชิกหรือใบสมัครที่ตรงเงื่อนไข' },
  'Approve & Assign Role': { 'zh-CN': '通过并分配角色', 'zh-TW': '通過並分配角色', ja: '承認して役割を割り当て', ko: '승인 및 역할 배정', th: 'อนุมัติและกำหนดบทบาท' },
  'Update Role': { 'zh-CN': '修改角色', 'zh-TW': '修改角色', ja: '役割を更新', ko: '역할 수정', th: 'อัปเดตบทบาท' },
  'Remove / Reject': { 'zh-CN': '移除/拒绝', 'zh-TW': '移除/拒絕', ja: '削除／拒否', ko: '제거 / 거부', th: 'นำออก / ปฏิเสธ' },
  'Search name or email...': { 'zh-CN': '搜索姓名或邮箱...', 'zh-TW': '搜尋姓名或郵箱...', ja: '名前またはメールで検索...', ko: '이름 또는 이메일 검색...', th: 'ค้นหาชื่อหรืออีเมล...' },
  'Member Role': { 'zh-CN': '成员角色', 'zh-TW': '成員角色', ja: 'メンバーの役割', ko: '멤버 역할', th: 'บทบาทสมาชิก' },
  'Manager': { 'zh-CN': '管理员', 'zh-TW': '管理員', ja: 'マネージャー', ko: '매니저', th: 'ผู้จัดการ' },
  'Member': { 'zh-CN': '会友', 'zh-TW': '會友', ja: 'メンバー', ko: '회원', th: 'สมาชิก' },
  'Group Leader': { 'zh-CN': '小组长', 'zh-TW': '小組長', ja: 'グループリーダー', ko: '그룹 리더', th: 'หัวหน้ากลุ่ม' },
  'Group Member': { 'zh-CN': '小组成员', 'zh-TW': '小組成員', ja: 'グループメンバー', ko: '그룹 멤버', th: 'สมาชิกกลุ่ม' },
  'Pending': { 'zh-CN': '待审核', 'zh-TW': '待審核', ja: '承認待ち', ko: '승인 대기', th: 'รออนุมัติ' },
  'All': { 'zh-CN': '全部', 'zh-TW': '全部', ja: 'すべて', ko: '전체', th: 'ทั้งหมด' },
  'Role updated successfully': { 'zh-CN': '角色已更新', 'zh-TW': '角色已更新', ja: '役割を更新しました', ko: '역할이 업데이트되었습니다', th: 'อัปเดตบทบาทแล้ว' },
  'Removed successfully': { 'zh-CN': '已移除', 'zh-TW': '已移除', ja: '削除しました', ko: '제거되었습니다', th: 'นำออกแล้ว' },
  'Join Codes': { 'zh-CN': '入会码管理', 'zh-TW': '入會碼管理', ja: '参加コード', ko: '가입 코드', th: 'รหัสเข้าร่วม' },
  'Standard Code': { 'zh-CN': '普通教会码', 'zh-TW': '普通教會碼', ja: '標準コード', ko: '일반 코드', th: 'รหัสมาตรฐาน' },
  'Staff Code': { 'zh-CN': '同工码', 'zh-TW': '同工碼', ja: 'スタッフコード', ko: '사역자 코드', th: 'รหัสเจ้าหน้าที่' },
  'Member Code': { 'zh-CN': '会友码', 'zh-TW': '會友碼', ja: 'メンバーコード', ko: '회원 코드', th: 'รหัสสมาชิก' },
  'Copy': { 'zh-CN': '复制', 'zh-TW': '複製', ja: 'コピー', ko: '복사', th: 'คัดลอก' },
  'Copied': { 'zh-CN': '已复制', 'zh-TW': '已複製', ja: 'コピー済み', ko: '복사됨', th: 'คัดลอกแล้ว' },
  'Close': { 'zh-CN': '关闭', 'zh-TW': '關閉', ja: '閉じる', ko: '닫기', th: 'ปิด' },
  'Error: ': { 'zh-CN': '错误：', 'zh-TW': '錯誤：', ja: 'エラー：', ko: '오류: ', th: 'ข้อผิดพลาด: ' },
  'Are you sure you want to remove/reject this member?': { 'zh-CN': '确定要移除/拒绝该成员吗？', 'zh-TW': '確定要移除/拒絕該成員嗎？', ja: 'このメンバーを削除／拒否しますか？', ko: '이 멤버를 제거/거부하시겠습니까?', th: 'ต้องการนำออก/ปฏิเสธสมาชิกนี้?' },
  'Error: Target church ID missing.': { 'zh-CN': '无法保存：未找到关联的教会ID。', 'zh-TW': '無法儲存：未找到關聯的教會ID。', ja: 'エラー：教会IDが見つかりません。', ko: '오류: 교회 ID가 없습니다.', th: 'ข้อผิดพลาด: ไม่พบรหัสคริสตจักร' },
  'Church code cannot be empty.': { 'zh-CN': '普通教会码不能为空', 'zh-TW': '普通教會碼不能為空', ja: '教会コードを入力してください', ko: '교회 코드를 입력하세요', th: 'รหัสคริสตจักรห้ามว่าง' },
  'Request timed out. Check network or RLS permissions.': { 'zh-CN': '请求超时，请检查网络或权限', 'zh-TW': '請求逾時，請檢查網路或權限', ja: 'リクエストがタイムアウトしました。ネットワークまたは権限を確認してください。', ko: '요청 시간 초과. 네트워크 또는 권한을 확인하세요.', th: 'หมดเวลา ตรวจสอบเครือข่ายหรือสิทธิ์' },
  'Blocked by database policy (RLS). Contact your platform admin.': { 'zh-CN': '保存被数据库拒绝（RLS权限不足）', 'zh-TW': '儲存被資料庫拒絕（RLS權限不足）', ja: 'データベースポリシー（RLS）により拒否されました。管理者に連絡してください。', ko: '데이터베이스 정책(RLS)에 의해 차단됨. 관리자에게 문의하세요.', th: 'ถูกบล็อกโดยนโยบายฐานข้อมูล (RLS) ติดต่อผู้ดูแล' },
  'Join codes updated!': { 'zh-CN': '加入码更新成功！', 'zh-TW': '加入碼更新成功！', ja: '参加コードを更新しました！', ko: '가입 코드가 업데이트되었습니다!', th: 'อัปเดตรหัสเข้าร่วมแล้ว!' },
  'Join code copied to clipboard': { 'zh-CN': '加入码已复制到剪贴板', 'zh-TW': '加入碼已複製到剪貼簿', ja: '参加コードをコピーしました', ko: '가입 코드가 복사되었습니다', th: 'คัดลอกรหัสแล้ว' },
  'Loading...': { 'zh-CN': '加载中...', 'zh-TW': '載入中...', ja: '読み込み中...', ko: '로딩 중...', th: 'กำลังโหลด...' },
  'TOTAL': { 'zh-CN': '总成员', 'zh-TW': '總成員', ja: '合計', ko: '전체', th: 'รวม' },
  'PENDING': { 'zh-CN': '待审核', 'zh-TW': '待審核', ja: '承認待ち', ko: '승인 대기', th: 'รออนุมัติ' },
  'Manage': { 'zh-CN': '设置', 'zh-TW': '設定', ja: '管理', ko: '관리', th: 'จัดการ' },
  'Admin:': { 'zh-CN': '主管理员:', 'zh-TW': '主管理員:', ja: '管理者：', ko: '관리자: ', th: 'ผู้ดูแล: ' },
  'Manage Join Codes': { 'zh-CN': '管理加入码', 'zh-TW': '管理加入碼', ja: '参加コードを管理', ko: '가입 코드 관리', th: 'จัดการรหัสเข้าร่วม' },
  'Fast join codes for different roles': { 'zh-CN': '设置不同角色的快速加入码', 'zh-TW': '設定不同角色的快速加入碼', ja: '役割ごとの参加コード', ko: '역할별 빠른 가입 코드', th: 'รหัสเข้าร่วมสำหรับแต่ละบทบาท' },
  'Members joining with this code require manual approval.': { 'zh-CN': '新成员使用此码加入后需要管理员手动审核。', 'zh-TW': '新成員使用此碼加入後需要管理員手動審核。', ja: 'このコードで参加するメンバーは手動承認が必要です。', ko: '이 코드로 가입하면 수동 승인이 필요합니다.', th: 'สมาชิกที่ใช้รหัสนี้ต้องได้รับการอนุมัติด้วยตนเอง' },
  'Save Codes': { 'zh-CN': '保存设置', 'zh-TW': '儲存設定', ja: 'コードを保存', ko: '코드 저장', th: 'บันทึกรหัส' },
  'Scan this code to quickly join the church': { 'zh-CN': '扫描此码即可快速加入教会', 'zh-TW': '掃描此碼即可快速加入教會', ja: 'このコードをスキャンして教会に参加', ko: '이 코드를 스캔하여 교회에 가입', th: 'สแกนรหัสนี้เพื่อเข้าร่วมคริสตจักร' },
};

/** Translate a UI string (keyed by its English text) to the given language. */
export function tr(en: string, language: string): string {
  const entry = UI[en];
  if (!entry) return en;
  return entry[language as Lang] || en;
}
